# Generated by Django 4.1.4 on 2023-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetproficiency',
            old_name='co1',
            new_name='co',
        ),
        migrations.RenameField(
            model_name='targetproficiency',
            old_name='co2',
            new_name='l1',
        ),
        migrations.RenameField(
            model_name='targetproficiency',
            old_name='co3',
            new_name='l2',
        ),
        migrations.RenameField(
            model_name='targetproficiency',
            old_name='co4',
            new_name='l3',
        ),
        migrations.RemoveField(
            model_name='targetproficiency',
            name='co5',
        ),
        migrations.AlterField(
            model_name='targetproficiency',
            name='tpl',
            field=models.CharField(default='', max_length=15),
        ),
    ]
